const exampleFiles = [
    // { name: 'cursor_rules.jpeg', type: 'image/jpeg', url: '/examples/cursor_rules.jpeg' },
    // { name: 'download.png', type: 'image/png', url: '/examples/download.png' },
    { name: 'kfc.png', type: 'image/png', url: '/examples/kfc.png' },
    { name: 'logo_jersey.png', type: 'image/png', url: '/examples/logo_jersey.png' },
    { name: 'logo_hard.png', type: 'image/png', url: '/examples/logo_hard.png' },
    { name: 'menu.png', type: 'image/png', url: '/examples/menu.png' },
    { name: 'phunt.png', type: 'image/png', url: '/examples/phunt.png' },
    { name: 'phunt2.png', type: 'image/png', url: '/examples/phunt2.png' },
    { name: 'Luna.png', type: 'image/png', url: '/examples/Luna.png' },
    { name: 'us.jpg', type: 'image/jpg', url: '/examples/us.jpg' },
    { name: 'financials.png', type: 'image/png', url: '/examples/financials.png' },
    { name: 'pirros_123.png', type: 'image/png', url: '/examples/pirros_123.png' },
    { name: 'pirros_1234.png', type: 'image/png', url: '/examples/pirros_1234.png' },
    { name: 'pirros_12345.png', type: 'image/png', url: '/examples/pirros_12345.png' },
    { name: 'pirros_same0.png', type: 'image/png', url: '/examples/pirros_same0.png' },
    { name: 'pirros_same1.png', type: 'image/png', url: '/examples/pirros_same1.png' },
    { name: 'pirros.png', type: 'image/png', url: '/examples/pirros.png' },
    { name: 'pirros2.png', type: 'image/png', url: '/examples/pirros2.png' },
    { name: 'pirros3.png', type: 'image/png', url: '/examples/pirros3.png' },
    { name: 'pirros4.png', type: 'image/png', url: '/examples/pirros4.png' },
    { name: 'github.png', type: 'image/png', url: '/examples/github.png' },
    { name: 'github2.png', type: 'image/png', url: '/examples/github2.png' },
    { name: 'page1.png', type: 'image/png', url: '/examples/page1.png' },
    { name: 'page2.png', type: 'image/png', url: '/examples/page2.png' },
    { name: 'page3.png', type: 'image/png', url: '/examples/page3.png' },
    { name: 'page4.png', type: 'image/png', url: '/examples/page4.png' },
    { name: 'page5.png', type: 'image/png', url: '/examples/page5.png' },
    { name: 'datasheet.png', type: 'image/png', url: '/examples/datasheet.png' },
    { name: 'circuit3.png', type: 'image/png', url: '/examples/circuit3.png' },
    { name: 'circuit2.png', type: 'image/png', url: '/examples/circuit2.png' },
    { name: 'circuit.png', type: 'image/png', url: '/examples/circuit.png' },
    { name: 'sequence.png', type: 'image/png', url: '/examples/sequence.png' },
    { name: 'pic-0.png', type: 'image/png', url: '/examples/pic-0.png' },
    { name: 'pic-1.png', type: 'image/png', url: '/examples/pic-1.png' },
    { name: 'login.png', type: 'image/png', url: '/examples/login.png' },
    { name: 'invoice.png', type: 'image/png', url: '/examples/invoice.png' },
    { name: 'hvac.png', type: 'image/png', url: '/examples/hvac.png' },
    { name: 'speakers.png', type: 'image/png', url: '/examples/speakers.png' },
    { name: 'code.png', type: 'image/png', url: '/examples/code.png' },
    { name: 'deto-1.png', type: 'image/png', url: '/examples/deto-1.png' },
    { name: 'deto-2.png', type: 'image/png', url: '/examples/deto-2.png' },
    { name: 'runway.png', type: 'image/png', url: '/examples/runway.png' },
    { name: 'kitchen.png', type: 'image/jpg', url: '/examples/kitchen.png' },
    { name: 'cambodia-visa.jpg', type: 'image/jpg', url: '/examples/cambodia-visa.jpg' },
    { name: 'ai-conference-floor-plan.png', type: 'image/png', url: '/examples/ai-conference-floor-plan.png' },
    { name: 'vai.png', type: 'image/png', url: '/examples/vai.png' },
    { name: 'chemicals.png', type: 'image/png', url: '/examples/chemicals.png' },
    { name: 'clerk.png', type: 'image/png', url: '/examples/clerk.png' },
    { name: 'speaker.png', type: 'image/png', url: '/examples/speaker.png' },
    { name: 'bankruptecy.png', type: 'image/png', url: '/examples/bankruptecy.png' },
    { name: 'bio.png', type: 'image/png', url: '/examples/bio.png' },
    { name: 'fb-ad.png', type: 'image/png', url: '/examples/fb-ad.png' },
    { name: 'demonslayer.jpg', type: 'image/jpg', url: '/examples/demonslayer.jpg' },
    { name: 'not_like_us.mp3', type: 'audio/mpeg', url: '/examples/not_like_us.mp3' },
    { name: 'restaurant.png', type: 'image/png', url: '/examples/restaurant.png' },
    { name: 'techcrunch_pitchdeck.xlsx', type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', url: '/examples/techcrunch_pitchdeck.xlsx' },
    { name: 'Untitled_document.docx', type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', url: '/examples/Untitled_document.docx' },
    { name: 'webcam', type: 'webcam', url: '/examples/webcam' },


]

export default exampleFiles